'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class student_studentprofile_view

    '''<summary>
    '''studentprofile_view1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents studentprofile_view1 As Global.permatapintar.studentprofile_view1

    '''<summary>
    '''parentprofile_view1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents parentprofile_view1 As Global.permatapintar.parentprofile_view

    '''<summary>
    '''studentschool_view1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents studentschool_view1 As Global.permatapintar.studentschool_view

    '''<summary>
    '''studentuni_view1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents studentuni_view1 As Global.permatapintar.studentuni_view

    '''<summary>
    '''ukm1_history_list1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ukm1_history_list1 As Global.permatapintar.ukm1_history_list

    '''<summary>
    '''ukm2_history_list1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ukm2_history_list1 As Global.permatapintar.ukm2_history_list

    '''<summary>
    '''ppcs_history_list1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ppcs_history_list1 As Global.permatapintar.ppcs_history_list
End Class
