'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class komputer2010
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.komputer2010", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Saya sama sekali tidak seperti ini .
        '''</summary>
        Friend Shared ReadOnly Property AgreeLevel1() As String
            Get
                Return ResourceManager.GetString("AgreeLevel1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Saya tidaklah sangat seperti ini .
        '''</summary>
        Friend Shared ReadOnly Property AgreeLevel2() As String
            Get
                Return ResourceManager.GetString("AgreeLevel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Saya adalah seperti ini .
        '''</summary>
        Friend Shared ReadOnly Property AgreeLevel3() As String
            Get
                Return ResourceManager.GetString("AgreeLevel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Saya memang seperti ini .
        '''</summary>
        Friend Shared ReadOnly Property AgreeLevel4() As String
            Get
                Return ResourceManager.GetString("AgreeLevel4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Saya memang sangat seperti ini .
        '''</summary>
        Friend Shared ReadOnly Property AgreeLevel5() As String
            Get
                Return ResourceManager.GetString("AgreeLevel5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.	Tidak Pernah.
        '''</summary>
        Friend Shared ReadOnly Property AnswerPage03_1() As String
            Get
                Return ResourceManager.GetString("AnswerPage03_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2.	Kurang daripada 5 kali seminggu.
        '''</summary>
        Friend Shared ReadOnly Property AnswerPage03_2() As String
            Get
                Return ResourceManager.GetString("AnswerPage03_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.	6 – 10 kali seminggu.
        '''</summary>
        Friend Shared ReadOnly Property AnswerPage03_3() As String
            Get
                Return ResourceManager.GetString("AnswerPage03_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4.	Lebih daripada 10 kali seminggu.
        '''</summary>
        Friend Shared ReadOnly Property AnswerPage03_4() As String
            Get
                Return ResourceManager.GetString("AnswerPage03_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seterusnya .
        '''</summary>
        Friend Shared ReadOnly Property btnNext() As String
            Get
                Return ResourceManager.GetString("btnNext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kemaskini .
        '''</summary>
        Friend Shared ReadOnly Property btnUpdate() As String
            Get
                Return ResourceManager.GetString("btnUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jawapan Anda.
        '''</summary>
        Friend Shared ReadOnly Property lblAPage02() As String
            Get
                Return ResourceManager.GetString("lblAPage02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pilihan Penilaian.
        '''</summary>
        Friend Shared ReadOnly Property lblJawapan() As String
            Get
                Return ResourceManager.GetString("lblJawapan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sila nyatakan perasaan anda berdasarkan gambar yang dipaparkan..
        '''</summary>
        Friend Shared ReadOnly Property lblperasaan() As String
            Get
                Return ResourceManager.GetString("lblperasaan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kemahiran komputer.
        '''</summary>
        Friend Shared ReadOnly Property lblQPage02() As String
            Get
                Return ResourceManager.GetString("lblQPage02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Soalan.
        '''</summary>
        Friend Shared ReadOnly Property lblSoalan() As String
            Get
                Return ResourceManager.GetString("lblSoalan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adakah anda mempunyai komputer peribadi/ komputer riba/ netbook di rumah?.
        '''</summary>
        Friend Shared ReadOnly Property Q001() As String
            Get
                Return ResourceManager.GetString("Q001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ya.
        '''</summary>
        Friend Shared ReadOnly Property Q001_1() As String
            Get
                Return ResourceManager.GetString("Q001_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tidak.
        '''</summary>
        Friend Shared ReadOnly Property Q001_2() As String
            Get
                Return ResourceManager.GetString("Q001_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nyatakan kekerapan anda menggunakan komputer dalam tempoh seminggu?.
        '''</summary>
        Friend Shared ReadOnly Property Q002() As String
            Get
                Return ResourceManager.GetString("Q002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1-3 Kali.
        '''</summary>
        Friend Shared ReadOnly Property Q002_1() As String
            Get
                Return ResourceManager.GetString("Q002_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 4-6 Kali.
        '''</summary>
        Friend Shared ReadOnly Property Q002_2() As String
            Get
                Return ResourceManager.GetString("Q002_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lebih dari 6.
        '''</summary>
        Friend Shared ReadOnly Property Q002_3() As String
            Get
                Return ResourceManager.GetString("Q002_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nyatakan jumlah jam  anda menggunakan komputer dalam tempoh seminggu?.
        '''</summary>
        Friend Shared ReadOnly Property Q003() As String
            Get
                Return ResourceManager.GetString("Q003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kurang daripada 1 jam.
        '''</summary>
        Friend Shared ReadOnly Property Q003_1() As String
            Get
                Return ResourceManager.GetString("Q003_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2-4 jam .
        '''</summary>
        Friend Shared ReadOnly Property Q003_2() As String
            Get
                Return ResourceManager.GetString("Q003_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lebih dari 4 jam.
        '''</summary>
        Friend Shared ReadOnly Property Q003_3() As String
            Get
                Return ResourceManager.GetString("Q003_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adakah terdapat perkhidmatan internet di rumah anda?.
        '''</summary>
        Friend Shared ReadOnly Property Q004() As String
            Get
                Return ResourceManager.GetString("Q004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ya.
        '''</summary>
        Friend Shared ReadOnly Property Q004_1() As String
            Get
                Return ResourceManager.GetString("Q004_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tidak.
        '''</summary>
        Friend Shared ReadOnly Property Q004_2() As String
            Get
                Return ResourceManager.GetString("Q004_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adakah terdapat perkhidmatan internet di sekolah anda?.
        '''</summary>
        Friend Shared ReadOnly Property Q005() As String
            Get
                Return ResourceManager.GetString("Q005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ya.
        '''</summary>
        Friend Shared ReadOnly Property Q005_1() As String
            Get
                Return ResourceManager.GetString("Q005_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tidak.
        '''</summary>
        Friend Shared ReadOnly Property Q005_2() As String
            Get
                Return ResourceManager.GetString("Q005_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adakah anda menggunakan komputer di luar waktu persekolahan?.
        '''</summary>
        Friend Shared ReadOnly Property Q006() As String
            Get
                Return ResourceManager.GetString("Q006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ya.
        '''</summary>
        Friend Shared ReadOnly Property Q006_1() As String
            Get
                Return ResourceManager.GetString("Q006_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tidak.
        '''</summary>
        Friend Shared ReadOnly Property Q006_2() As String
            Get
                Return ResourceManager.GetString("Q006_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Di manakah anda menggunakan komputer di  luar waktu persekolahan?.
        '''</summary>
        Friend Shared ReadOnly Property Q007() As String
            Get
                Return ResourceManager.GetString("Q007", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Makmal sekolah.
        '''</summary>
        Friend Shared ReadOnly Property Q007_1() As String
            Get
                Return ResourceManager.GetString("Q007_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rumah.
        '''</summary>
        Friend Shared ReadOnly Property Q007_2() As String
            Get
                Return ResourceManager.GetString("Q007_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kafe siber.
        '''</summary>
        Friend Shared ReadOnly Property Q007_3() As String
            Get
                Return ResourceManager.GetString("Q007_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pejabat Ibu/bapa.
        '''</summary>
        Friend Shared ReadOnly Property Q007_4() As String
            Get
                Return ResourceManager.GetString("Q007_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lain-lain tempat.
        '''</summary>
        Friend Shared ReadOnly Property Q007_5() As String
            Get
                Return ResourceManager.GetString("Q007_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apakah tujuan anda menggunakan komputer di  luar waktu persekolahan?.
        '''</summary>
        Friend Shared ReadOnly Property Q008() As String
            Get
                Return ResourceManager.GetString("Q008", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bermain &quot;Games&quot;.
        '''</summary>
        Friend Shared ReadOnly Property Q008_1() As String
            Get
                Return ResourceManager.GetString("Q008_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Internet.
        '''</summary>
        Friend Shared ReadOnly Property Q008_2() As String
            Get
                Return ResourceManager.GetString("Q008_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Menyiapkan tugasan sekolah.
        '''</summary>
        Friend Shared ReadOnly Property Q008_3() As String
            Get
                Return ResourceManager.GetString("Q008_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mempelajari suatu perisian yang baru.
        '''</summary>
        Friend Shared ReadOnly Property Q008_4() As String
            Get
                Return ResourceManager.GetString("Q008_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lain-lain tujuan.
        '''</summary>
        Friend Shared ReadOnly Property Q008_5() As String
            Get
                Return ResourceManager.GetString("Q008_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dari manakah anda mendapat pengalaman tentang kemahiran komputer:.
        '''</summary>
        Friend Shared ReadOnly Property Q009() As String
            Get
                Return ResourceManager.GetString("Q009", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Belajar sendiri.
        '''</summary>
        Friend Shared ReadOnly Property Q009_1() As String
            Get
                Return ResourceManager.GetString("Q009_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ain-lain tempat.
        '''</summary>
        Friend Shared ReadOnly Property Q009_10() As String
            Get
                Return ResourceManager.GetString("Q009_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buku-buku / majalah.
        '''</summary>
        Friend Shared ReadOnly Property Q009_2() As String
            Get
                Return ResourceManager.GetString("Q009_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kelab komputer.
        '''</summary>
        Friend Shared ReadOnly Property Q009_3() As String
            Get
                Return ResourceManager.GetString("Q009_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kelas ICT.
        '''</summary>
        Friend Shared ReadOnly Property Q009_4() As String
            Get
                Return ResourceManager.GetString("Q009_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kursus.
        '''</summary>
        Friend Shared ReadOnly Property Q009_5() As String
            Get
                Return ResourceManager.GetString("Q009_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rakan-rakan.
        '''</summary>
        Friend Shared ReadOnly Property Q009_6() As String
            Get
                Return ResourceManager.GetString("Q009_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keluarga.
        '''</summary>
        Friend Shared ReadOnly Property Q009_7() As String
            Get
                Return ResourceManager.GetString("Q009_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Belajar sendiri.
        '''</summary>
        Friend Shared ReadOnly Property Q009_8() As String
            Get
                Return ResourceManager.GetString("Q009_8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Media massa.
        '''</summary>
        Friend Shared ReadOnly Property Q009_9() As String
            Get
                Return ResourceManager.GetString("Q009_9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kenapa anda menggunakan komputer?.
        '''</summary>
        Friend Shared ReadOnly Property Q010() As String
            Get
                Return ResourceManager.GetString("Q010", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minat.
        '''</summary>
        Friend Shared ReadOnly Property Q010_1() As String
            Get
                Return ResourceManager.GetString("Q010_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keperluan pembelajaran.
        '''</summary>
        Friend Shared ReadOnly Property Q010_2() As String
            Get
                Return ResourceManager.GetString("Q010_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bermain &quot;games&quot;.
        '''</summary>
        Friend Shared ReadOnly Property Q010_3() As String
            Get
                Return ResourceManager.GetString("Q010_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paksaan Ibu bapa/guru .
        '''</summary>
        Friend Shared ReadOnly Property Q010_4() As String
            Get
                Return ResourceManager.GetString("Q010_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lain-lain sebab.
        '''</summary>
        Friend Shared ReadOnly Property Q010_5() As String
            Get
                Return ResourceManager.GetString("Q010_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adakah anda berminat untuk mempelajari kemahiran komputer jika anda berpeluang?.
        '''</summary>
        Friend Shared ReadOnly Property Q011() As String
            Get
                Return ResourceManager.GetString("Q011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ya.
        '''</summary>
        Friend Shared ReadOnly Property Q011_1() As String
            Get
                Return ResourceManager.GetString("Q011_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tidak.
        '''</summary>
        Friend Shared ReadOnly Property Q011_2() As String
            Get
                Return ResourceManager.GetString("Q011_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apakah kaedah  pembelajaran yang anda minati?.
        '''</summary>
        Friend Shared ReadOnly Property Q012() As String
            Get
                Return ResourceManager.GetString("Q012", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pembelajaran berbantukan  jurulatih .
        '''</summary>
        Friend Shared ReadOnly Property Q012_1() As String
            Get
                Return ResourceManager.GetString("Q012_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pembelajaran kendiri menggunakan modul bercetak.
        '''</summary>
        Friend Shared ReadOnly Property Q012_2() As String
            Get
                Return ResourceManager.GetString("Q012_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pembelajaran dalam talian (online).
        '''</summary>
        Friend Shared ReadOnly Property Q012_3() As String
            Get
                Return ResourceManager.GetString("Q012_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Perisian Microsoft Office.
        '''</summary>
        Friend Shared ReadOnly Property Q013() As String
            Get
                Return ResourceManager.GetString("Q013", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telah dipelajari.
        '''</summary>
        Friend Shared ReadOnly Property Q013_1() As String
            Get
                Return ResourceManager.GetString("Q013_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ingin dipelajari .
        '''</summary>
        Friend Shared ReadOnly Property Q013_2() As String
            Get
                Return ResourceManager.GetString("Q013_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Perisian OpenOffice.org.
        '''</summary>
        Friend Shared ReadOnly Property Q014() As String
            Get
                Return ResourceManager.GetString("Q014", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Perisian penyuntingan grafik.
        '''</summary>
        Friend Shared ReadOnly Property Q015() As String
            Get
                Return ResourceManager.GetString("Q015", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Perisian penyuntingan video.
        '''</summary>
        Friend Shared ReadOnly Property Q016() As String
            Get
                Return ResourceManager.GetString("Q016", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Perisian penyuntingan audio.
        '''</summary>
        Friend Shared ReadOnly Property Q017() As String
            Get
                Return ResourceManager.GetString("Q017", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Perisian penyuntingan animasi.
        '''</summary>
        Friend Shared ReadOnly Property Q018() As String
            Get
                Return ResourceManager.GetString("Q018", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Perisian  pengarangan multimedia .
        '''</summary>
        Friend Shared ReadOnly Property Q019() As String
            Get
                Return ResourceManager.GetString("Q019", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bahasa Pengaturcaraan Visual Basic.
        '''</summary>
        Friend Shared ReadOnly Property Q020() As String
            Get
                Return ResourceManager.GetString("Q020", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bahasa Pengaturcaraan  C.
        '''</summary>
        Friend Shared ReadOnly Property Q021() As String
            Get
                Return ResourceManager.GetString("Q021", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bahasa Pengaturcaraan  Java.
        '''</summary>
        Friend Shared ReadOnly Property Q022() As String
            Get
                Return ResourceManager.GetString("Q022", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Baik pulih komputer.
        '''</summary>
        Friend Shared ReadOnly Property Q023() As String
            Get
                Return ResourceManager.GetString("Q023", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pembangunan Laman Web.
        '''</summary>
        Friend Shared ReadOnly Property Q024() As String
            Get
                Return ResourceManager.GetString("Q024", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pembangunan Permainan.
        '''</summary>
        Friend Shared ReadOnly Property Q025() As String
            Get
                Return ResourceManager.GetString("Q025", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pembangunan Perisian Kursus (perisian pembelajaran).
        '''</summary>
        Friend Shared ReadOnly Property Q026() As String
            Get
                Return ResourceManager.GetString("Q026", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pembangunan Sistem Maklumat Pengurusan.
        '''</summary>
        Friend Shared ReadOnly Property Q027() As String
            Get
                Return ResourceManager.GetString("Q027", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pencarian Maklumat secara berkesan.
        '''</summary>
        Friend Shared ReadOnly Property Q028() As String
            Get
                Return ResourceManager.GetString("Q028", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Facebook.
        '''</summary>
        Friend Shared ReadOnly Property Q029() As String
            Get
                Return ResourceManager.GetString("Q029", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Blog.
        '''</summary>
        Friend Shared ReadOnly Property Q030() As String
            Get
                Return ResourceManager.GetString("Q030", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wiki.
        '''</summary>
        Friend Shared ReadOnly Property Q031() As String
            Get
                Return ResourceManager.GetString("Q031", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aplikasi telefon mudahalih.
        '''</summary>
        Friend Shared ReadOnly Property Q032() As String
            Get
                Return ResourceManager.GetString("Q032", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aplikasi Facebook.
        '''</summary>
        Friend Shared ReadOnly Property Q033() As String
            Get
                Return ResourceManager.GetString("Q033", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saya menggunakan  bahan-bahan dari laman web  untuk tujuan pembelajaran dengan menyatakan sumber rujukan..
        '''</summary>
        Friend Shared ReadOnly Property Q034() As String
            Get
                Return ResourceManager.GetString("Q034", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saya menyatakan sumber rujukan  bagi bahan-bahan yang diambil dari laman web untuk laporan tugasan .
        '''</summary>
        Friend Shared ReadOnly Property Q035() As String
            Get
                Return ResourceManager.GetString("Q035", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saya mengamalkan salin-tampal (copy-paste) dalam tugasan saya..
        '''</summary>
        Friend Shared ReadOnly Property Q036() As String
            Get
                Return ResourceManager.GetString("Q036", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saya memuat turun (download) bahan yang dibenarkan daripada Internet..
        '''</summary>
        Friend Shared ReadOnly Property Q037() As String
            Get
                Return ResourceManager.GetString("Q037", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saya menggunakan bahasa yang sopan semasa berinteraksi menggunakan mel elektronik (e-mail).
        '''</summary>
        Friend Shared ReadOnly Property Q038() As String
            Get
                Return ResourceManager.GetString("Q038", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saya menggunakan bahasa yang sopan semasa berbual/bersimbang  maya (chatting).
        '''</summary>
        Friend Shared ReadOnly Property Q039() As String
            Get
                Return ResourceManager.GetString("Q039", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saya menggunakan bahasa yang sopan semasa berinteraksi dalam kumpulan perbincangan elektronik (e-group).
        '''</summary>
        Friend Shared ReadOnly Property Q040() As String
            Get
                Return ResourceManager.GetString("Q040", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saya menggunakan bahasa yang sopan semasa menggunakan Laman Web Sosial seperti Facebook atau  MySpace.
        '''</summary>
        Friend Shared ReadOnly Property Q041() As String
            Get
                Return ResourceManager.GetString("Q041", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saya menyebarkan maklumat palsu kepada orang lain..
        '''</summary>
        Friend Shared ReadOnly Property Q042() As String
            Get
                Return ResourceManager.GetString("Q042", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saya membaca dokumen di dalam komputer peribadi orang lain..
        '''</summary>
        Friend Shared ReadOnly Property Q043() As String
            Get
                Return ResourceManager.GetString("Q043", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saya membuka kata laluan orang lain..
        '''</summary>
        Friend Shared ReadOnly Property Q044() As String
            Get
                Return ResourceManager.GetString("Q044", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saya membuka dan menonton video yang berunsur keganasan..
        '''</summary>
        Friend Shared ReadOnly Property Q045() As String
            Get
                Return ResourceManager.GetString("Q045", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saya membuka  video yang berunsur lucah dari laman web..
        '''</summary>
        Friend Shared ReadOnly Property Q046() As String
            Get
                Return ResourceManager.GetString("Q046", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saya menonton video yang berunsur pendidikan dari laman web..
        '''</summary>
        Friend Shared ReadOnly Property Q047() As String
            Get
                Return ResourceManager.GetString("Q047", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saya  menyamar sebagai orang lain dalam  Laman Web Sosial.
        '''</summary>
        Friend Shared ReadOnly Property Q048() As String
            Get
                Return ResourceManager.GetString("Q048", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tujuan saya melayari laman web adalah untuk (boleh memilih lebih daripada satu jawapan).
        '''</summary>
        Friend Shared ReadOnly Property Q049() As String
            Get
                Return ResourceManager.GetString("Q049", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Berbual/simbang elektronik (Chatting).
        '''</summary>
        Friend Shared ReadOnly Property Q049_1() As String
            Get
                Return ResourceManager.GetString("Q049_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bermain dengan permainan dalam talian.
        '''</summary>
        Friend Shared ReadOnly Property Q049_2() As String
            Get
                Return ResourceManager.GetString("Q049_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Menonton video .
        '''</summary>
        Friend Shared ReadOnly Property Q049_3() As String
            Get
                Return ResourceManager.GetString("Q049_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mencari kawan.
        '''</summary>
        Friend Shared ReadOnly Property Q049_4() As String
            Get
                Return ResourceManager.GetString("Q049_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mencari maklumat untuk tugasan.
        '''</summary>
        Friend Shared ReadOnly Property Q049_5() As String
            Get
                Return ResourceManager.GetString("Q049_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mencari maklumat untuk menambah lagi ilmu pengetahuan.
        '''</summary>
        Friend Shared ReadOnly Property Q049_6() As String
            Get
                Return ResourceManager.GetString("Q049_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property Q050() As String
            Get
                Return ResourceManager.GetString("Q050", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
