'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pelajar_koko_pencapaian_update
    
    '''<summary>
    '''studentprofile_view_header1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents studentprofile_view_header1 As Global.permatapintar.studentprofile_view_header
    
    '''<summary>
    '''koko_list1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents koko_list1 As Global.permatapintar.koko_list
    
    '''<summary>
    '''koko_pencapaian_update1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents koko_pencapaian_update1 As Global.permatapintar.koko_pencapaian_update
End Class
