'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.7905
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class semak_view_04

    '''<summary>
    '''lblSoalan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSoalan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJawapan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJawapan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNo01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo01 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQ001 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQ001 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q1 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblNo02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo02 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQ002 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQ002 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q2 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblNo03 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo03 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQ003 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQ003 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q3 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblNo04 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo04 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQ004 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQ004 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q4 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblNo05 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo05 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQ005 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQ005 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q5 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblNo06 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo06 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQ006 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQ006 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q6 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblNo07 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo07 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQ007 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQ007 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q7 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblNo08 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo08 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQ008 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQ008 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Q8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q8 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblNo09 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo09 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQ009 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQ009 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Q9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q9 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblNo10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQ010 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQ010 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Q10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q10 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblNo11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQ011 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQ011 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Q11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q11 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblNo12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQ012 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQ012 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Q12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q12 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblNo13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQ013 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQ013 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Q13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q13 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblNo14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQ014 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQ014 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Q14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q14 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblNo15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQ015 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQ015 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Q15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q15 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblNo16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNo16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQ016 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQ016 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Q16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Q16 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
End Class
