'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class admin_detail_disiplin
    
    '''<summary>
    '''disiplinMultiView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents disiplinMultiView As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''caseDetailView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caseDetailView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''Disiplin_Case_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Disiplin_Case_Detail As Global.KPP_MS.Disiplin_Case_Detail
    
    '''<summary>
    '''warningLetterList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents warningLetterList As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''Disiplin_Letter_List control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Disiplin_Letter_List As Global.KPP_MS.Disiplin_Letter_List
    
    '''<summary>
    '''warningLetterForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents warningLetterForm As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''Disiplin_Warning_Letter_Form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Disiplin_Warning_Letter_Form As Global.KPP_MS.Disiplin_Warning_Letter_Form
End Class
