'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pengajar_password_baru
    
    '''<summary>
    '''txtloginUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtloginUsername As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtloginPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtloginPassword As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtnewPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnewPassword As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Btnsimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btnsimpan As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''Btnback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btnback As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
