'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class ppcs_users_year_update

    '''<summary>
    '''admin_ppcsusers_view1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents admin_ppcsusers_view1 As Global.permatapintar.admin_ppcsusers_view

    '''<summary>
    '''admin_ppcsusers_year_update1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents admin_ppcsusers_year_update1 As Global.permatapintar.admin_ppcsusers_year_update
End Class
