'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class admin_studentprofile_view
    
    '''<summary>
    '''studentprofile_view1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents studentprofile_view1 As Global.permatapintar.studentprofile_view1
    
    '''<summary>
    '''parentprofile_view1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents parentprofile_view1 As Global.permatapintar.parentprofile_view
    
    '''<summary>
    '''studentschool_list1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents studentschool_list1 As Global.permatapintar.studentschool_list
    
    '''<summary>
    '''StudentUni_list1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StudentUni_list1 As Global.permatapintar.StudentUni_list
    
    '''<summary>
    '''ukm1_history_list1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ukm1_history_list1 As Global.permatapintar.ukm1_history_list
    
    '''<summary>
    '''ukm2_history_list1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ukm2_history_list1 As Global.permatapintar.ukm2_history_list
    
    '''<summary>
    '''ppcs_history_list1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ppcs_history_list1 As Global.permatapintar.ppcs_history_list
    
    '''<summary>
    '''ddlExamYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlExamYear As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlMenudesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMenudesc As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnExecute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExecute As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ddlPPCSDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPPCSDate As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlPPCSStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPPCSStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnPPCS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPPCS As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''flaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents flaging As Global.System.Web.UI.HtmlControls.HtmlSelect
    
    '''<summary>
    '''Simpanflag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Simpanflag As Global.System.Web.UI.WebControls.Button
End Class
