'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class exam_Transcript
    
    '''<summary>
    '''txtbreadcrum1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbreadcrum1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnExaminationTranscript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExaminationTranscript As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnOfficialTranscript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOfficialTranscript As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''ExaminationTranscript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExaminationTranscript As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlyear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlyear As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlcampus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlcampus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlprogram control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlprogram As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlstudent_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlstudent_Year As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlexam_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlexam_Name As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlclass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlclass As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''datRespondent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datRespondent As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''BtnGenerate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnGenerate As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''BtnPrintkoko control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPrintkoko As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''BtnPrintkokoBM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPrintkokoBM As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''OfficialTranscript control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficialTranscript As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddl_TrasncriptYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_TrasncriptYear As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddl_TranscriptCampus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_TranscriptCampus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddl_TranscriptProgram control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_TranscriptProgram As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddl_TranscriptType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_TranscriptType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TranscriptRespondent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TranscriptRespondent As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnOfficialBI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOfficialBI As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnOfficialBM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOfficialBM As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
