'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class hostel_Update
    
    '''<summary>
    '''previousPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previousPage As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''txtbreadcrum1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbreadcrum1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnEditHostelInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditHostelInformation As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnEditRoomInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditRoomInformation As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''EditHostelInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditHostelInformation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ddlHostel_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHostel_Year As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlHostel_Semester control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHostel_Semester As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlHostel_Campus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHostel_Campus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlHostel_Block control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHostel_Block As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlHostel_BlockLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHostel_BlockLevel As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtHostel_RoomQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHostel_RoomQuantity As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Btnsimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btnsimpan As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''EditRoomInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EditRoomInformation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''datRespondent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datRespondent As Global.System.Web.UI.WebControls.GridView
End Class
