'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pengarah_laporan_kehadiran_table
    
    '''<summary>
    '''ddlAttendanceYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAttendanceYear As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAttendanceMonth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAttendanceMonth As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAttendanceCampus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAttendanceCampus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAttendanceProgram control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAttendanceProgram As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAttendanceLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAttendanceLevel As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAttendaceCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAttendaceCourse As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAttendanceClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAttendanceClass As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''datRespondent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datRespondent As Global.System.Web.UI.WebControls.GridView
End Class
