'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class student_homepage
    
    '''<summary>
    '''student_Photo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents student_Photo As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''student_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents student_Name As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''student_Mykad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents student_Mykad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''student_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents student_ID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''student_Sex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents student_Sex As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''student_Race control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents student_Race As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''student_Religion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents student_Religion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''student_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents student_Email As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''student_FonNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents student_FonNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''student_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents student_Address As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''student_City control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents student_City As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''student_State control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents student_State As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''student_PostCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents student_PostCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''student_Level control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents student_Level As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''student_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents student_Year As Global.System.Web.UI.WebControls.Label
End Class
