'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pelajar_daftar_baru
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''btnTutorial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTutorial As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnStudentInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStudentInfo As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnParentInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnParentInfo As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''btnLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogout As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''StudentTutorial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StudentTutorial As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''StudentInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StudentInformation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtstudentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstudentName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''student_Photo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents student_Photo As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''uploadPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uploadPhoto As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''txtstudentMykad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstudentMykad As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlRace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRace As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlReligion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReligion As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rbtn_Male control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtn_Male As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rbtn_Female control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtn_Female As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txtstudentEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstudentEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtstudentPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstudentPhone As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtstudentAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstudentAddress As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtstudentCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstudentCity As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtstudentPostcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstudentPostcode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlState As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtstudentYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstudentYear As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtstudentLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstudentLevel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtstudentSem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstudentSem As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnUpdateStudentInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateStudentInfo As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''FamilyInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FamilyInformation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Parent1_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parent1_Name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Parent2_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parent2_Name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Parent1_IC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parent1_IC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Parent2_IC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parent2_IC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Parent1_MobileNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parent1_MobileNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Parent2_MobileNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parent2_MobileNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Parent1_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parent1_Email As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Parent2_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parent2_Email As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Parent1_Connection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parent1_Connection As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Parent2_Connection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parent2_Connection As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Parent1_Work control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parent1_Work As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Parent2_Work control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parent2_Work As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlsalaryP1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlsalaryP1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlsalaryP2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlsalaryP2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Parent1_RadioStatusAlive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parent1_RadioStatusAlive As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''Parent1_RadioStatusPassAway control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parent1_RadioStatusPassAway As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''Parent2_RadioStatusAlive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parent2_RadioStatusAlive As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''Parent2_RadioStatusPassAway control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Parent2_RadioStatusPassAway As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''Btnsimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btnsimpan As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
