'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class class_Update
    
    '''<summary>
    '''class_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents class_Name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''class_year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents class_year As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlclass_Level control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlclass_Level As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlstaff_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlstaff_ID As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtstd_number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstd_number As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Btnsimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btnsimpan As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''Btnback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btnback As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
