'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class parent_imagePayment_details

    '''<summary>
    '''hyperlinkInvoiceInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hyperlinkInvoiceInformation As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''View_StudentInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents View_StudentInvoice As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Inv_StudentName_LBL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Inv_StudentName_LBL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Inv_Number_LBL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Inv_Number_LBL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Inv_Totalamount_LBL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Inv_Totalamount_LBL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Inv_Outstanding_LBL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Inv_Outstanding_LBL As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''datRespondent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datRespondent As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txt_desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_desc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnUpdateInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnUpdateInvoice As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''BtnBayar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBayar As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''BtnRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnRefresh As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
