'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ppcs_dobyear_summary
    
    '''<summary>
    '''ddlPPCSDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPPCSDate As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlStudentReligion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStudentReligion As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlDOB_Year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDOB_Year As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlPPCSStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPPCSStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlTawaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTawaran As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnSearch02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch02 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''dat_Age_State control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dat_Age_State As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblMsgTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgTop As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlStudentRace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStudentRace As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlPPCSStatusBangsa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPPCSStatusBangsa As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlTawaran2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTawaran2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnSearch01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch01 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''dat_Age control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dat_Age As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
End Class
